# Generated by Django 5.2 on 2025-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='landlord_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant_answers',
            field=models.JSONField(default=dict),
        ),
    ]
